//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public int UserID { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> IDRef { get; set; }
        public string IdRole { get; set; }
        public Nullable<int> Emp_No { get; set; }
        public Nullable<short> IDType { get; set; }
        public Nullable<int> OB_SEQ { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsDepartment { get; set; }
        public string Email { get; set; }
        public Nullable<bool> EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<bool> PhoneNumberConfirmed { get; set; }
        public Nullable<bool> TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public Nullable<bool> LockoutEnabled { get; set; }
        public Nullable<int> AccessFailedCount { get; set; }
        public string UR_NoMobile { get; set; }
        public Nullable<System.DateTime> UR_DateReg { get; set; }
        public string UR_Ask { get; set; }
        public string UR_Answer { get; set; }
        public string UR_Notes { get; set; }
        public Nullable<System.DateTime> UR_SysDate { get; set; }
        public Nullable<bool> UR_IsActive { get; set; }
    }
}
