//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Nullable<int> EmpNo { get; set; }
        public string IdentityNumber { get; set; }
        public byte IDOrg { get; set; }
        public string Name { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> IdentityDate { get; set; }
        public string Qualification { get; set; }
        public string YearofQualification { get; set; }
        public string Specification { get; set; }
        public string JobNumber { get; set; }
        public Nullable<System.DateTime> JobStartMinistry { get; set; }
        public Nullable<System.DateTime> JobStartSchool { get; set; }
        public Nullable<System.DateTime> JobStartCurrent { get; set; }
        public string Level { get; set; }
        public string Degree { get; set; }
        public string PhoneHome { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Comments { get; set; }
        public string classesNumber { get; set; }
        public Nullable<int> JobId { get; set; }
    
        public virtual Job Job { get; set; }
    }
}
