//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuidProgram
    {
        public int Id { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<int> SemesterId { get; set; }
        public string ProgramName { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string Occasion { get; set; }
        public Nullable<int> BeneficiariesNo { get; set; }
        public Nullable<int> StudentNo { get; set; }
        public string Responsiveness { get; set; }
        public Nullable<int> BeneficiariesType { get; set; }
    }
}
