//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incoming
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Source { get; set; }
        public string Subject { get; set; }
        public string FileNumber { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> Attachment { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string FileLocation { get; set; }
        public string Comment { get; set; }
    }
}
