//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class newscategory
    {
        public int category_id { get; set; }
        public string category_name { get; set; }
        public string category_description { get; set; }
        public Nullable<bool> Is_Ative { get; set; }
    }
}
