//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public long news_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public Nullable<byte> IDOrg { get; set; }
        public Nullable<System.DateTime> date_posted { get; set; }
        public string news_title { get; set; }
        public string news_content { get; set; }
        public Nullable<System.DateTime> date_updated { get; set; }
        public Nullable<byte> news_status { get; set; }
        public Nullable<byte> comment_status { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
    }
}
