//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public School()
        {
            this.Teachers = new HashSet<Teacher>();
        }
    
        public int SchoolId { get; set; }
        public Nullable<int> IDRef { get; set; }
        public string school_Code { get; set; }
        public string School_Name { get; set; }
        public string logo { get; set; }
        public string Mobile1 { get; set; }
        public string Mobile2 { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> Type { get; set; }
        public string Area { get; set; }
        public System.TimeSpan TimeStartWork { get; set; }
        public System.TimeSpan TimeEndWork { get; set; }
        public int VacationNumber { get; set; }
        public string StatisticaFigure { get; set; }
        public string EducationalLevel { get; set; }
        public string Office { get; set; }
        public string Address { get; set; }
        public Nullable<int> TotalClass { get; set; }
        public Nullable<int> TotalStudents { get; set; }
        public Nullable<int> TotalStaff { get; set; }
        public Nullable<int> RentedBuildingsNo { get; set; }
        public Nullable<int> GovernmentBuildingsNo { get; set; }
        public string YearFounded { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string FaceBook { get; set; }
        public string GoogleMap { get; set; }
        public string LevelSchool { get; set; }
        public Nullable<System.DateTime> DateWork { get; set; }
        public string City { get; set; }
        public string ManagerName { get; set; }
        public string LicenseNum { get; set; }
        public string Notes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}
