//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public string KKey { get; set; }
        public string KVal { get; set; }
        public string Title { get; set; }
        public string Group { get; set; }
        public string DefaultValue { get; set; }
    }
}
