//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TbOrgnizationInfo
    {
        public byte IDOrg { get; set; }
        public string OrgnizeInfo { get; set; }
        public string Address { get; set; }
        public string NoMobile { get; set; }
        public string NoPhone { get; set; }
        public string NoFax { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public byte[] PicLogo { get; set; }
        public Nullable<bool> IsLogoVisible { get; set; }
    }
}
