//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int IDTeacher { get; set; }
        public Nullable<int> SchoolId { get; set; }
        public string Name { get; set; }
        public string BirthLocation { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Status { get; set; }
        public string Sons { get; set; }
        public string SonsYounger6 { get; set; }
        public string SonsYounger24 { get; set; }
        public string SonsOLder24 { get; set; }
        public string Email { get; set; }
        public string MailBox { get; set; }
        public string PostalCode { get; set; }
        public string Mobile { get; set; }
        public string Telephon1 { get; set; }
        public string Telephon2 { get; set; }
        public string Address { get; set; }
        public string Religion { get; set; }
        public string EnName { get; set; }
        public string NationalCard { get; set; }
        public string TypeWork { get; set; }
        public Nullable<short> YearsExperice { get; set; }
        public string Note { get; set; }
        public string TypeStuday { get; set; }
        public string SepName { get; set; }
        public byte[] PicScanerWork { get; set; }
        public Nullable<bool> IsWork { get; set; }
    
        public virtual School School { get; set; }
    }
}
