//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Education.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string TypeUser { get; set; }
        public Nullable<int> NoEmp { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<short> CodeIDM { get; set; }
        public Nullable<short> LevelTypeMang { get; set; }
        public Nullable<bool> S1 { get; set; }
        public Nullable<bool> S2 { get; set; }
        public Nullable<bool> S3 { get; set; }
        public Nullable<bool> S4 { get; set; }
        public Nullable<bool> S5 { get; set; }
        public Nullable<bool> S6 { get; set; }
        public Nullable<bool> S7 { get; set; }
        public Nullable<bool> S8 { get; set; }
        public Nullable<bool> S9 { get; set; }
        public Nullable<bool> S10 { get; set; }
        public Nullable<bool> S11 { get; set; }
        public Nullable<bool> S12 { get; set; }
        public Nullable<bool> S13 { get; set; }
        public Nullable<bool> S14 { get; set; }
        public Nullable<bool> S15 { get; set; }
        public Nullable<bool> S16 { get; set; }
        public Nullable<bool> S17 { get; set; }
        public Nullable<bool> S18 { get; set; }
        public Nullable<bool> S19 { get; set; }
        public Nullable<bool> S20 { get; set; }
        public Nullable<bool> S21 { get; set; }
        public Nullable<bool> S22 { get; set; }
        public Nullable<bool> S23 { get; set; }
        public Nullable<bool> S24 { get; set; }
        public Nullable<bool> S25 { get; set; }
        public Nullable<bool> S26 { get; set; }
        public Nullable<bool> S27 { get; set; }
        public Nullable<bool> S28 { get; set; }
        public Nullable<bool> S29 { get; set; }
        public Nullable<bool> S30 { get; set; }
        public Nullable<bool> IsLogin { get; set; }
        public Nullable<short> GrpID { get; set; }
    }
}
